name: Terraform Validation

on:
  push:
    branches:
      - infra_features  # Trigger on pushes to the infra_features branch
  pull_request:
    branches:
      - infra_features  # Optionally, trigger on pull requests targeting infra_features
  # workflow_dispatch:  # Allow manual trigger

jobs:
  validate:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 2: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 5: Validate Terraform
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Step 7: Plan Terraform
      - name: Terraform Plan
        working-directory: ./terraform
        if: github.event_name == 'pull_request'
        run: terraform plan